# Generated by Django 4.0.1 on 2022-01-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frexco', '0003_alter_region_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frexco.region'),
        ),
    ]
