# Generated by Django 4.0.1 on 2022-01-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frexco', '0006_alter_fruit_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
