# Generated by Django 4.0.1 on 2022-01-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frexco', '0007_alter_fruit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[{'Sul', 'S'}, ('CO', 'Centro-Oeste'), ('SE', 'Sudeste'), ('NE', 'Nordeste'), ('N', 'Norte')], max_length=3, unique=True),
        ),
    ]
