# Generated by Django 4.0.1 on 2022-01-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frexco', '0009_alter_region_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(choices=[('Sul', 'S'), ('Centro-Oeste', 'CO'), ('Sudeste', 'SE'), ('Nordeste', 'NE'), ('Norte', 'N')], max_length=12, unique=True),
        ),
    ]
